### ISSUE TITLE
Profile Picture

### ISSUE THREAD

**Issue by costinberty** [gnoverse/dsocial#105]
Users will be able to set themselves a profile picture.

**Comment by costinberty** [comment]
For the backend part we will need to wait for the [](https://github.com/gnolang/gno/pull/1983) to be merged

**Comment by jefft0** [comment]
r/demo/profile is merged https://github.com/gnolang/gno/pull/1983

**Comment by jefft0** [comment]
https://github.com/gnolang/dsocial/pull/127 is merged.

**Comment by costinberty** [comment]
feature implemented
